MasterTech/Components/NavigationMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using MasterTech.Models;

namespace MasterTech.Components
{

    public class NavigationMenuViewComponent : ViewComponent
    {
        private IServiceRepository repository;

        public NavigationMenuViewComponent(IServiceRepository repo)
        {
            repository = repo;
        }

        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedCategory = RouteData?.Values["category"];
            return View(repository.Services
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x));
        }
    }
}

MasterTech/Controllers/ServiceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MasterTech.Models;
using Microsoft.AspNetCore.Mvc;
using MasterTech.Models.ViewModels;

namespace MasterTech.Controllers
{
    public class ServiceController : Controller
    {
        private IServiceRepository repository;
        public int PageSize = 4;
        public ServiceController(IServiceRepository repo)
        {
            repository = repo;   
        }
        public ViewResult List(string category, int servicePage = 1) =>
            View(new ServicesListViewModel
            {
                Services = repository.Services
                    .Where(s => category == null || s.Category == category)
                    .OrderBy(s => s.ServiceID)
                    .Skip((servicePage - 1) * PageSize)
                    .Take(PageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = servicePage,
                    ItemsPerPage = PageSize,
                    TotalItems = category == null ?
                    repository.Services.Count() :
                    repository.Services.Where(e =>
                    e.Category == category).Count()
                },
                CurrentCategory = category
            });
    }
}

MasterTech/Views/_Layout.cshtml
@model Microsoft.AspNetCore.Http.HttpContextAccessor

<!DOCTYPE html>

<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="~/css/base.css" type="text/css">
    <link rel="stylesheet" href="~/css/color-theme.css" type="text/css">
    @await Html.PartialAsync((string)ViewBag.Title + "CssPartial")
    <link rel="shortcut icon" href="~/img/favicon.ico" type="image/x-icon">
    <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">
    <title>@ViewBag.Title</title>
</head>

<body>
    @*<div class="top">
        <div class="left">
            <a href="tel:380542281488" class="header-link tel hover">+38 054 228-14-88</a>
        </div>
        <ul class="right">
            <li><a class="header-link hover" asp-controller="Account" asp-action="Login">login</a></li>
            <li><a class="header-link hover" asp-controller="Account" asp-action="Register">sign up</a></li>
        </ul>
    </div>*@
    <header>
        <div class="bottom">
            <div class="left">
                <a class="header-link hover" asp-controller="Home" asp-action="Index"><div class="logo-wrapper">MasterTech</div></a>
            </div>
            <ul class="right">
                <li><a class="header-link hover" asp-controller="Home" asp-action="Help">Help</a></li>
                <li><a class="header-link hover" asp-controller="Home" asp-action="About">About</a></li>
                <li><a class="header-link hover" asp-controller="Service" asp-action="List">Services</a></li>
                <li><a class="header-link hover" asp-controller="Home" asp-action="Contacts">Contacts</a></li>
            </ul>
        </div>
    </header>

    <main>
        @RenderBody()
    </main>

    <footer>
        <div class="upper-footer">
            <div class="item-wrapper div1">
                <p class="links">полезное</p>
                <ul class="useful-links">
                    <li><a class="footer-link hover" href="#">closures & notices</a></li>
                    <li><a class="footer-link hover" href="#">privacy policy</a></li>
                    <li><a class="footer-link hover" href="#">cookie policy</a></li>
                    <li><a class="footer-link hover" href="#">terms & conditions</a></li>
                    <li><a class="footer-link hover" href="#">sitemap</a></li>
                </ul>
            </div>
            <div class="item-wrapper div2">
                <p class="links">социальные сети</p>
                <ul class="social-links">
                    <li><a href="https://uk-ua.facebook.com/" target="_blank" class="icon-link"><img src="~/img/facebook.png" alt="facebook"></a></li>
                    <li><a href="https://twitter.com/?lang=ru" target="_blank" class="icon-link"><img src="~/img/twitter.png" alt="twitter"></a></li>
                    <li><a href="https://www.instagram.com/" target="_blank" class="icon-link"><img src="~/img/instagram.png" alt="instagram"></a></li>
                    <li><a href="https://www.youtube.com/" target="_blank" class="icon-link"><img src="~/img/youtube.png" alt="youtube"></a></li>
                </ul>
            </div>
        </div>
        <div class="copyright">Copyright &copy; 2021</div>
    </footer>
</body>
</html>

MasterTech/Views/_ServiceLayout.cshtml
<!DOCTYPE html>

<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="~/css/base.css" type="text/css">
    <link rel="stylesheet" href="~/css/color-theme.css" type="text/css">
    <link rel="stylesheet"
          asp-href-include="/lib/bootstrap/dist/**/*.min.css"
          asp-href-exclude="**/*-reboot*,**/*-grid*" />
    <link rel="stylesheet" href="~/lib/css/bootstrap.css">
    <link rel="shortcut icon" href="~/img/favicon.ico" type="image/x-icon">
    <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">
    <title>@ViewBag.Title</title>
</head>

<body>
    @*<div class="top">
        <div class="left">
            <a href="tel:380542281488" class="header-link tel hover">+38 054 228-14-88</a>
        </div>
        <ul class="right">
            <li><a class="header-link hover" asp-controller="Account" asp-action="Login">login</a></li>
            <li><a class="header-link hover" asp-controller="Account" asp-action="Register">sign up</a></li>
        </ul>
    </div>*@
    <header>
        <div class="bottom">
            <div class="left">
                <a class="header-link hover" asp-controller="Home" asp-action="Index"><div class="logo-wrapper">MasterTech</div></a>
            </div>
            <ul class="right">
                <li><a class="header-link hover" asp-controller="Home" asp-action="Help">Help</a></li>
                <li><a class="header-link hover" asp-controller="Home" asp-action="About">About</a></li>
                <li><a class="header-link hover" asp-controller="Service" asp-action="List">Services</a></li>
                <li><a class="header-link hover" asp-controller="Home" asp-action="Contacts">Contacts</a></li>
            </ul>
        </div>
    </header>

    <main>
        <div class="concrete-margin row m-1 p-1">
            <div class="row m-1 p-1">
                <div id="categories" class="col-3">
                    @await Component.InvokeAsync("NavigationMenu")
                </div>
                <div class="col-9">
                    @RenderBody()
                </div>
            </div>
        </div>
</main>

    <footer>
        <div class="upper-footer">
            <div class="item-wrapper div1">
                <p class="links">полезное</p>
                <ul class="useful-links">
                    <li><a class="footer-link hover" href="#">closures & notices</a></li>
                    <li><a class="footer-link hover" href="#">privacy policy</a></li>
                    <li><a class="footer-link hover" href="#">cookie policy</a></li>
                    <li><a class="footer-link hover" href="#">terms & conditions</a></li>
                    <li><a class="footer-link hover" href="#">sitemap</a></li>
                </ul>
            </div>
            <div class="item-wrapper div2">
                <p class="links">социальные сети</p>
                <ul class="social-links">
                    <li><a href="https://uk-ua.facebook.com/" target="_blank" class="icon-link"><img src="~/img/facebook.png" alt="facebook"></a></li>
                    <li><a href="https://twitter.com/?lang=ru" target="_blank" class="icon-link"><img src="~/img/twitter.png" alt="twitter"></a></li>
                    <li><a href="https://www.instagram.com/" target="_blank" class="icon-link"><img src="~/img/instagram.png" alt="instagram"></a></li>
                    <li><a href="https://www.youtube.com/" target="_blank" class="icon-link"><img src="~/img/youtube.png" alt="youtube"></a></li>
                </ul>
            </div>
        </div>
        <div class="copyright">Copyright &copy; 2021</div>
    </footer>
</body>
</html>